### ISSUE TITLE
zhmakeindex crashes on MacOS 10.13.3

### ISSUE THREAD

**Issue by stefan11** [leo-liu/zhmakeindex#13]
Error log below. I tried to compile the files from source. Some experiences:

1) Pathes to directories are hardwired. I had to replicate your setup.

2) No binary is created by install.sh, so I am lost.

I do not speak Chinese, I am sorry.

zhmakeindex -o grammatical-theory.scd grammatical-theory.scx
fatal error: unexpected signal during runtime execution
[signal 0xa code=0x2 addr=0xc46e0ba484 pc=0x38893]

runtime stack:
runtime.throw(0x6d0e70, 0x2a)
	C:/GreenSoft/Go/src/runtime/panic.go:543 +0xa0
runtime.sigpanic()
	C:/GreenSoft/Go/src/runtime/sigpanic_unix.go:12 +0x62
runtime.mHeap_FreeSpanLocked(0xc29b00, 0xc86248, 0xc208100100, 0x0)
	C:/GreenSoft/Go/src/runtime/mheap.go:696 +0x163
runtime.mHeap_Grow(0xc29b00, 0x30, 0x0)
	C:/GreenSoft/Go/src/runtime/mheap.go:592 +0x2ce
runtime.mHeap_AllocSpanLocked(0xc29b00, 0x2c, 0x2e09a)
	C:/GreenSoft/Go/src/runtime/mheap.go:473 +0x588
runtime.mHeap_Alloc_m(0xc29b00, 0x2c, 0x100000000, 0xc311d8)
	C:/GreenSoft/Go/src/runtime/mheap.go:380 +0x130
runtime.mHeap_Alloc.func1()
	C:/GreenSoft/Go/src/runtime/mheap.go:427 +0x48
runtime.systemstack(0x7ffeefbffa80)
	C:/GreenSoft/Go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0xc29b00, 0x2c, 0x10100000000, 0xc81088)
	C:/GreenSoft/Go/src/runtime/mheap.go:428 +0x66
runtime.largeAlloc(0x58000, 0x0, 0xc20000000c)
	C:/GreenSoft/Go/src/runtime/malloc.go:684 +0xa2
runtime.mallocgc.func3()
	C:/GreenSoft/Go/src/runtime/malloc.go:604 +0x3a
runtime.systemstack(0xc22e30)
	C:/GreenSoft/Go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	C:/GreenSoft/Go/src/runtime/proc1.go:682

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	C:/GreenSoft/Go/src/runtime/asm_amd64.s:216 fp=0xc20802fd38 sp=0xc20802fd30
runtime.mallocgc(0x58000, 0x14db20, 0xc200000000, 0xc2080afef0)
	C:/GreenSoft/Go/src/runtime/malloc.go:605 +0x774 fp=0xc20802fe00 sp=0xc20802fd38
runtime.newarray(0x14db20, 0x800, 0x14db20)
	C:/GreenSoft/Go/src/runtime/malloc.go:716 +0xc8 fp=0xc20802fe38 sp=0xc20802fe00
runtime.hashGrow(0x1100a0, 0xc208046270)
	C:/GreenSoft/Go/src/runtime/hashmap.go:782 +0x8a fp=0xc20802fe68 sp=0xc20802fe38
runtime.mapassign1(0x1100a0, 0xc208046270, 0x9bac40, 0x9bac48)
	C:/GreenSoft/Go/src/runtime/hashmap.go:490 +0x54b fp=0xc20802ff08 sp=0xc20802fe68
code.google.com/p/zhmakeindex/CJK.init()
	C:/Users/Leo/Documents/GoProjects/src/code.google.com/p/zhmakeindex/CJK/radicalstrokes.go:75875 +0xe7 fp=0xc20802ff40 sp=0xc20802ff08
main.init()
	C:/Users/Leo/Documents/GoProjects/src/code.google.com/p/zhmakeindex/style.go:380 +0x9f fp=0xc20802ffa0 sp=0xc20802ff40
runtime.main()
	C:/GreenSoft/Go/src/runtime/proc.go:83 +0x1bb fp=0xc20802ffe0 sp=0xc20802ffa0
runtime.goexit()
	C:/GreenSoft/Go/src/runtime/asm_amd64.s:2458 +0x1 fp=0xc20802ffe8 sp=0xc20802ffe0
make: *** [grammatical-theory.pdf] Error 2

**Comment by leo-liu** [comment]
Sorry for the late reply. Since I don't have macOS for testing, maybe you can try to build zhmakeindex yourself. After running `install.sh` or simply `go install`, the executable binary will be in $GOPATH/bin. That's the convention of all go apps. Or you can run `go build` to build the program.

BTW, The paths are not hardwired. Paths in error messages are only paths I built on my PC.

**Comment by stefan11** [comment]
Cool! Thank you! It works now. The binary was under ~/go/bin. As for 1.: The external libraries you used had to be in specific subdirectories, which where defined somewhere in your setup. I replicated this. Now everything works and we are happy. =:-)

**Comment by leo-liu** [comment]
Prebuilt binary of ver 1.2
https://github.com/leo-liu/zhmakeindex/releases/tag/zhmakeindex-1.2

**Comment by bubifengyun** [comment]
@stefan11 do you use `zhmakeindex` in latex or elsewhere? I had download the zip file, unzip it, and I find that my latex file cannot find `zhmakeindex`.
