### ISSUE TITLE
fatal: 不是一个 git 仓库（或者任何父目录）

### ISSUE THREAD

**Issue by bubifengyun** [leo-liu/zhmakeindex#15]
Linux下，下载后，

```
sudo apt-get install golang
```

然后到目录下，运行

```
sudo ./install.sh 
```

报错，

<pre>
sudo ./install.sh 
fatal: 不是一个 git 仓库（或者任何父目录）：.git
radical_collator.go:8:2: cannot find package "github.com/leo-liu/zhmakeindex/CJK" in any of:
	/usr/lib/go-1.8/src/github.com/leo-liu/zhmakeindex/CJK (from $GOROOT)
	/root/go/src/github.com/leo-liu/zhmakeindex/CJK (from $GOPATH)
style.go:15:2: cannot find package "github.com/leo-liu/zhmakeindex/kpathsea" in any of:
	/usr/lib/go-1.8/src/github.com/leo-liu/zhmakeindex/kpathsea (from $GOROOT)
	/root/go/src/github.com/leo-liu/zhmakeindex/kpathsea (from $GOPATH)
input.go:14:2: cannot find package "github.com/yasushi-saito/rbtree" in any of:
	/usr/lib/go-1.8/src/github.com/yasushi-saito/rbtree (from $GOROOT)
	/root/go/src/github.com/yasushi-saito/rbtree (from $GOPATH)
main.go:15:2: cannot find package "golang.org/x/text/encoding" in any of:
	/usr/lib/go-1.8/src/golang.org/x/text/encoding (from $GOROOT)
	/root/go/src/golang.org/x/text/encoding (from $GOPATH)
main.go:16:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
	/usr/lib/go-1.8/src/golang.org/x/text/encoding/simplifiedchinese (from $GOROOT)
	/root/go/src/golang.org/x/text/encoding/simplifiedchinese (from $GOPATH)
main.go:17:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
	/usr/lib/go-1.8/src/golang.org/x/text/encoding/traditionalchinese (from $GOROOT)
	/root/go/src/golang.org/x/text/encoding/traditionalchinese (from $GOPATH)
main.go:18:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
	/usr/lib/go-1.8/src/golang.org/x/text/encoding/unicode (from $GOROOT)
	/root/go/src/golang.org/x/text/encoding/unicode (from $GOPATH)
input.go:12:2: cannot find package "golang.org/x/text/transform" in any of:
	/usr/lib/go-1.8/src/golang.org/x/text/transform (from $GOROOT)
	/root/go/src/golang.org/x/text/transform (from $GOPATH)

</pre>

**Comment by bubifengyun** [comment]
想在 latex 中使用 zhmakeindex。百度必应了很久，一直没有找到一个好的示例，没办法就想直接安装 zhmakeindex ，结果报错。在 texlive 2018 貌似没有收录 zhmakeindex 这个包。谢谢大神了。

**Comment by leo-liu** [comment]
CTAN 有预编译版本。

bubifengyun <notifications@github.com> 于 2018年7月5日周四 11:04写道：

**Comment by bubifengyun** [comment]
谢谢，我已经找到了编译好的 bin 文件。但是使用必应和百度搜索了一下，仅仅找到这么两个网页提到 

- http://www.ituring.com.cn/article/207412
- https://www.zhihu.com/question/51727820
- http://bbs.ctex.org/forum.php?mod=viewthread&tid=78544
- http://bbs.ctex.org/forum.php?mod=viewthread&tid=77913
- https://en.wikibooks.org/wiki/LaTeX/Installing_Extra_Packages

我根据上述网页，参考这里。想把 zhmakeindex 安装到 linux_x64 的 texlive 2018 安装目录下。

```
sudo cp bin/linux_x64/zhmakeindex /usr/local/texlive/2018/bin/x86_64-linux/
sudo cp doc /usr/local/texlive/2018/texmf-dist/doc/support/zhmakeindex -r
sudo ln -s /usr/local/texlive/2018/bin/x86_64-linux/zhmakeindex /usr/local/bin/
```

不知道我的理解对不对，把可执行文件和doc下文件放到这里了。然后检测安装情况

```
$ kpsewhich zhmakeindex
$ tlmgr info zhmakeindex
下面是输出
tlmgr: cannot find package zhmakeindex, searching for other matches:

Packages containing `zhmakeindex' in their title/description:

Packages containing files matching `zhmakeindex':
```

貌似安装 zhmakeindex 包就是一个问题。怎么在 latex 下使用，还在摸索中。一直没有搜索到有`\usepackage{zhmakeindex}` 这样的语句。说明， zhmakeindex 还不能作为“正常的包”来用。特来请教这两个问题，一是如何安装 zhmakeindex并检测安装成功，一是如何在LaTeX下使用，我打算继续读这个源码，看看有没有收获，谢谢。

**Comment by leo-liu** [comment]
zhmakeindex 不是 TeX 宏包，而是可执行文件，它仅仅是一个程序。放在 $PATH 可找到的路径下就可以了，用法和 makeindex
程序一样。
二进制预编译版本在 CTAN 有，github release 也有。编译过的手册也在里面。

在 2018年7月6日 下午2:05，bubifengyun <notifications@github.com>写道：

**Comment by bubifengyun** [comment]
非常感谢，我已经用在 https://github.com/bubifengyun/deepin-bible 了，使用 bookdown 也可用实现精美的编辑了。我改用 imakeidx 代替 makeidx 可以更灵活的配置。只是像您排版中出现的页面带有字母序号的，还是出不来。zhmakeindex.mst 不适用于 xindy 排序。

**Comment by bubifengyun** [comment]
谢谢，已经解决啦。解决方案见这里。https://stackoverflow.com/questions/51236979/how-to-use-zhmakeindex-instead-of-makeindex-in-bookdown/51265313#51265313
